# Site settings
title: 'Veridu'
email: contact@veridu.github.io
description: > # this means to ignore newlines until "baseurl:"
  Veridu brings trust to the internet with a range of identity verification tools that are fast and easy for users, and reduce fraud for merchants.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://veridu.github.io" # the base hostname & protocol for your site
twitter_username: veridu
github_username:  veridu
sass:
  compressed: true
# Build settings
markdown: kramdown

# Gems
gems: []
